In [1]:
import pandas as pd

In [57]:
# 1) Разворачивание (заворачивание) данных
# - melt
# - pivot
# 2) Преобразование типов
# - pd.to_numeric
# - pd.to_datetime
# 3) Работа с Nan
# - fillna
# - dropna
# 4) Группировка
# - groupby

# Задание:
# 1) Скачать показатель с https://www.gapminder.org/data/
# 2) Преоброзовать в длинный формат
# 3) Удалить null, если есть
# 4) Преоброзовать типы
# 5) Сделать Группировка (стране, году)

In [20]:
df = pd.read_csv('../data/raw/aged_15plus_unemployment_rate_percent.csv')

In [23]:
df_melt = pd.melt(
    df, 
    id_vars='country', 
    var_name='year', 
    value_name='unemployment_15plus'
)

In [24]:
df_melt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16428 entries, 0 to 16427
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              16428 non-null  object
 1   year                 16428 non-null  object
 2   unemployment_15plus  4698 non-null   float64
dtypes: float64(1), object(2)
memory usage: 385.2+ KB

In [27]:
df_1 = df_melt.copy()

In [28]:
df_1['unemployment_15plus'] = df_1['unemployment_15plus'].fillna(-1)

In [29]:
df_1

            country  year  unemployment_15plus
0             Aruba  1947                 -1.0
1       Afghanistan  1947                 -1.0
2            Angola  1947                 -1.0
3          Anguilla  1947                 -1.0
4           Albania  1947                 -1.0
...             ...   ...                  ...
16423         Samoa  2020                 -1.0
16424         Yemen  2020                 -1.0
16425  South Africa  2020                 29.2
16426        Zambia  2020                 -1.0
16427      Zimbabwe  2020                 -1.0

[16428 rows x 3 columns]

In [31]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16428 entries, 0 to 16427
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              16428 non-null  object
 1   year                 16428 non-null  object
 2   unemployment_15plus  16428 non-null  float64
dtypes: float64(1), object(2)
memory usage: 385.2+ KB

In [33]:
df_melt = df_melt.dropna()

In [35]:
df_melt.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4698 entries, 209 to 16425
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              4698 non-null   object
 1   year                 4698 non-null   object
 2   unemployment_15plus  4698 non-null   float64
dtypes: float64(1), object(2)
memory usage: 146.8+ KB

In [37]:
df_melt['year'] = pd.to_numeric(df_melt['year'])

In [38]:
df_melt.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4698 entries, 209 to 16425
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              4698 non-null   object
 1   year                 4698 non-null   int64
 2   unemployment_15plus  4698 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 146.8+ KB

In [40]:
df_melt = df_melt.reset_index(drop=True)

In [47]:
df_melt[['country', 'unemployment_15plus']].groupby(by='country').agg('mean')

                  unemployment_15plus
country
Afghanistan                  6.998000
Albania                     12.850000
Algeria                     18.005385
American Samoa              12.484706
Angola                      12.718750
...                               ...
Vietnam                      1.890909
Wallis et Futuna            56.300000
Yemen                       14.404000
Zambia                      13.412857
Zimbabwe                     7.477778

[222 rows x 1 columns]

In [49]:
df_grp = df_melt[['country', 'unemployment_15plus']].groupby(by='country').agg(['mean', 'median', 'min', 'max', 'count'])

In [52]:
df_grp.loc['Russia']

unemployment_15plus  mean       7.44069
                     median     7.06000
                     min        4.50000
                     max       13.30000
                     count     29.00000
Name: Russia, dtype: float64

In [56]:
df_grp.sort_values(('unemployment_15plus', 'median'))

                 unemployment_15plus
                                mean  median    min    max count
country
Qatar                       0.391875   0.295   0.10   1.48    16
Cambodia                    1.380000   0.795   0.14   7.53    16
Myanmar                     1.940000   0.870   0.50   6.00     5
Chad                        0.915000   0.915   0.70   1.13     2
Rwanda                      6.440000   1.030   0.30  17.40     8
...                              ...     ...    ...    ...   ...
South Africa               27.065217  26.500  22.40  33.30    23
North Macedonia            28.300000  29.000  17.20  38.80    39
Reunion                    29.860000  29.500  19.10  37.70    25
Kosovo                     39.129412  39.700  26.00  57.00    17
Wallis et Futuna           56.300000  56.300  56.30  56.30     1

[222 rows x 5 columns]