In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
# Простая регрессионная модель.
# 1. Загрузка данных
# 2. Предварительная обработка данных
# 3. Выбор целевой переменной и признаков
# 4. Разделение выборки на обучающую и тестовую
# 5. Обучение модели
# 6. Получение предсказаний и оценка качества
# 7. Анализ коэффициентов модели

In [8]:
df_raw = pd.read_csv('../data/raw/Sleep_health_and_lifestyle_dataset.csv')

In [9]:
df_raw

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [10]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person ID                374 non-null    int64
 1   Gender                   374 non-null    object
 2   Age                      374 non-null    int64
 3   Occupation               374 non-null    object
 4   Sleep Duration           374 non-null    float64
 5   Quality of Sleep         374 non-null    int64
 6   Physical Activity Level  374 non-null    int64
 7   Stress Level             374 non-null    int64
 8   BMI Category             374 non-null    object
 9   Blood Pressure           374 non-null    object
 10  Heart Rate               374 non-null    int64
 11  Daily Steps              374 non-null    int64
 12  Sleep Disorder           155 non-null    object
dtypes: float64(1), int64(7), object(5)
memory usage: 38.1+ KB

In [12]:
df = df_raw[['Gender', 'Age', 'Sleep Duration', 'Quality of Sleep', 'Physical Activity Level', 'Stress Level', 'BMI Category', 'Heart Rate', 'Daily Steps']].copy()

In [13]:
df

,Gender,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Heart Rate,Daily Steps
0,Male,27,6.1,6,42,6,Overweight,77,4200
1,Male,28,6.2,6,60,8,Normal,75,10000
2,Male,28,6.2,6,60,8,Normal,75,10000
3,Male,28,5.9,4,30,8,Obese,85,3000
4,Male,28,5.9,4,30,8,Obese,85,3000
...,...,...,...,...,...,...,...,...,...
369,Female,59,8.1,9,75,3,Overweight,68,7000
370,Female,59,8.0,9,75,3,Overweight,68,7000
371,Female,59,8.1,9,75,3,Overweight,68,7000
372,Female,59,8.1,9,75,3,Overweight,68,7000
373,Female,59,8.1,9,75,3,Overweight,68,7000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Gender                   374 non-null    object
 1   Age                      374 non-null    int64
 2   Sleep Duration           374 non-null    float64
 3   Quality of Sleep         374 non-null    int64
 4   Physical Activity Level  374 non-null    int64
 5   Stress Level             374 non-null    int64
 6   BMI Category             374 non-null    object
 7   Heart Rate               374 non-null    int64
 8   Daily Steps              374 non-null    int64
dtypes: float64(1), int64(6), object(2)
memory usage: 26.4+ KB

In [15]:
df['Gender'].value_counts()

Gender
Male      189
Female    185
Name: count, dtype: int64

In [16]:
df['BMI Category'].value_counts()

BMI Category
Normal           195
Overweight       148
Normal Weight     21
Obese             10
Name: count, dtype: int64

In [19]:
df_processed = pd.get_dummies(df, columns=['Gender', 'BMI Category'], drop_first=True)

In [20]:
df_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         374 non-null    int64
 1   Sleep Duration              374 non-null    float64
 2   Quality of Sleep            374 non-null    int64
 3   Physical Activity Level     374 non-null    int64
 4   Stress Level                374 non-null    int64
 5   Heart Rate                  374 non-null    int64
 6   Daily Steps                 374 non-null    int64
 7   Gender_Male                 374 non-null    bool
 8   BMI Category_Normal Weight  374 non-null    bool
 9   BMI Category_Obese          374 non-null    bool
 10  BMI Category_Overweight     374 non-null    bool
dtypes: bool(4), float64(1), int64(6)
memory usage: 22.0 KB

In [21]:
y = df_processed['Stress Level']
X = df_processed.drop('Stress Level', axis=1)

In [22]:
y

0      6
1      8
2      8
3      8
4      8
      ..
369    3
370    3
371    3
372    3
373    3
Name: Stress Level, Length: 374, dtype: int64

In [23]:
X

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Heart Rate,Daily Steps,Gender_Male,BMI Category_Normal Weight,BMI Category_Obese,BMI Category_Overweight
0,27,6.1,6,42,77,4200,True,False,False,True
1,28,6.2,6,60,75,10000,True,False,False,False
2,28,6.2,6,60,75,10000,True,False,False,False
3,28,5.9,4,30,85,3000,True,False,True,False
4,28,5.9,4,30,85,3000,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...
369,59,8.1,9,75,68,7000,False,False,False,True
370,59,8.0,9,75,68,7000,False,False,False,True
371,59,8.1,9,75,68,7000,False,False,False,True
372,59,8.1,9,75,68,7000,False,False,False,True
373,59,8.1,9,75,68,7000,False,False,False,True

In [24]:
y.shape

(374,)

In [25]:
X.shape

(374, 10)

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [30]:
X_train

,Age,Sleep Duration,Quality of Sleep,Physical Activity Level,Heart Rate,Daily Steps,Gender_Male,BMI Category_Normal Weight,BMI Category_Obese,BMI Category_Overweight
192,43,6.5,6,45,72,6000,True,False,False,True
75,33,6.0,6,30,72,5000,True,False,False,False
84,35,7.5,8,60,70,8000,True,True,False,False
362,59,8.2,9,75,68,7000,False,False,False,True
16,29,6.5,5,40,80,4000,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...
71,33,6.1,6,30,72,5000,True,False,False,False
106,37,6.1,6,42,77,4200,False,False,False,True
270,49,6.1,6,90,75,10000,False,False,False,True
348,57,8.2,9,75,68,7000,False,False,False,True
102,36,7.2,8,60,68,7000,False,False,False,False

In [31]:
X_train.shape

(299, 10)

In [32]:
X_test.shape

(75, 10)

In [33]:
y_train.shape

(299,)

In [34]:
y_test.shape

(75,)

In [35]:
model = LinearRegression()

In [37]:
model.fit(X_train, y_train)

LinearRegression()

In [38]:
predictions = model.predict(X_test)

In [39]:
predictions

array([2.93226497, 7.42374618, 7.72758272, 2.93226497, 7.5377394 ,
       7.16487154, 7.60076548, 4.15400676, 3.04625819, 5.19007796,
       7.21583868, 5.69232554, 5.30407118, 7.5377394 , 5.30407118,
       7.85718645, 6.62925005, 7.21583868, 3.04625819, 4.09098068,
       5.4643391 , 5.21587639, 7.54979834, 4.31663087, 4.37965695,
       5.29201224, 7.21583868, 7.05087833, 7.05087833, 3.05025118,
       5.47639804, 4.38362476, 5.6413584 , 2.94831691, 7.90815359,
       4.15400676, 7.43580512, 5.57833232, 5.30407118, 5.25478459,
       7.11390441, 7.85718645, 7.84137291, 7.05087833, 5.07608474,
       4.15400676, 3.85567021, 5.70438448, 8.03751995, 5.59039126,
       2.82226475, 3.95863466, 7.90815359, 5.27890247, 4.36577223,
       2.82226475, 4.56507376, 8.03751995, 2.9872251 , 7.60076548,
       5.19007796, 5.84284351, 7.60076548, 5.6413584 , 4.26566373,
       7.54979834, 7.21583868, 2.93226497, 5.32986961, 5.1643281 ,
       4.09098068, 7.05087833, 2.92020603, 7.85718645, 2.99928404])

In [40]:
mae = mean_absolute_error(y_test, predictions)

In [41]:
mse = mean_squared_error(y_test, predictions)

In [42]:
r2 = r2_score(y_test, predictions)

In [43]:
rmse = np.sqrt(mse)

In [44]:
print(f'mae = {mae:.2f}')
print(f'mse = {mse:.2f}')
print(f'rmse = {rmse:.2f}')
print(f'R^2 = {r2:.2f}')

mae = 0.28
mse = 0.15
rmse = 0.39
R^2 = 0.95

In [46]:
df_processed['Stress Level'].describe()

count    374.000000
mean       5.385027
std        1.774526
min        3.000000
25%        4.000000
50%        5.000000
75%        7.000000
max        8.000000
Name: Stress Level, dtype: float64

In [47]:
model.coef_

array([ 6.30260799e-02, -5.09671381e-01, -9.28785058e-01, -9.26777948e-03,
        1.53281591e-01,  2.28494914e-04,  7.95517343e-01, -1.67418722e-01,
       -2.69232324e+00, -1.01479049e+00])

In [48]:
X.columns

Index(['Age', 'Sleep Duration', 'Quality of Sleep', 'Physical Activity Level',
       'Heart Rate', 'Daily Steps', 'Gender_Male',
       'BMI Category_Normal Weight', 'BMI Category_Obese',
       'BMI Category_Overweight'],
      dtype='object')

In [51]:
coef = pd.DataFrame(model.coef_, X.columns, columns=['Coef']).sort_values('Coef')

In [52]:
coef

                                Coef
BMI Category_Obese         -2.692323
BMI Category_Overweight    -1.014790
Quality of Sleep           -0.928785
Sleep Duration             -0.509671
BMI Category_Normal Weight -0.167419
Physical Activity Level    -0.009268
Daily Steps                 0.000228
Age                         0.063026
Heart Rate                  0.153282
Gender_Male                 0.795517

In [53]:
df['BMI Category'].value_counts()

BMI Category
Normal           195
Overweight       148
Normal Weight     21
Obese             10
Name: count, dtype: int64