In [1]:
import pandas as pd

In [3]:
# Работа с нексолькими датафреймами
# Объединение дф через concat
# Соединение дф через merge
# Сводные таблицы pivot_table

In [5]:
df_pop = pd.read_csv('../data/raw/pop.csv')

In [6]:
df_unemployment_15plus = pd.read_csv('../data/raw/aged_15plus_unemployment_rate_percent.csv')

In [8]:
df_pop = pd.melt(
    df_pop, 
    id_vars='country', 
    var_name='year', 
    value_name='population'
)

In [7]:
df_unemployment_15plus = pd.melt(df_unemployment_15plus, id_vars='country', var_name='year', value_name='unemployment_15plus')

In [9]:
df_pop.head(3)

       country  year population
0  Afghanistan  1800      3.28M
1       Angola  1800      1.57M
2      Albania  1800       400k

In [10]:
df_pop = df_pop.dropna()

In [11]:
df_pop.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59197 entries, 0 to 59296
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     59197 non-null  object
 1   year        59197 non-null  object
 2   population  59197 non-null  object
dtypes: object(3)
memory usage: 1.8+ MB

In [12]:
df_pop['year'] = pd.to_numeric(df_pop['year'])

In [14]:
df_pop['population'] = pd.to_numeric(
    ((
        df_pop['population'].astype(str)\
        .str.replace('M', 'e6'))\
        .str.replace('k', 'e3'))\
        .str.replace('B', 'e9')\
)

In [15]:
df_pop.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59197 entries, 0 to 59296
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     59197 non-null  object
 1   year        59197 non-null  int64
 2   population  59197 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.8+ MB

In [16]:
df_unemployment_15plus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16428 entries, 0 to 16427
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              16428 non-null  object
 1   year                 16428 non-null  object
 2   unemployment_15plus  4698 non-null   float64
dtypes: float64(1), object(2)
memory usage: 385.2+ KB

In [17]:
df_unemployment_15plus = df_unemployment_15plus.dropna()

In [18]:
df_unemployment_15plus['year'] = pd.to_numeric(df_unemployment_15plus['year'])

In [19]:
df_pop.head(3)

       country  year  population
0  Afghanistan  1800   3280000.0
1       Angola  1800   1570000.0
2      Albania  1800    400000.0

In [23]:
df_unemployment_15plus.head(3)

    country  year  unemployment_15plus
209     USA  1947                  3.9
431     USA  1948                  3.8
653     USA  1949                  5.9

In [25]:
df_merged = pd.merge(
    df_pop, 
    df_unemployment_15plus, 
    how='inner',
    left_on=['country', 'year'],
    right_on=['country', 'year']
)

In [26]:
df_unemployment_15plus[(df_unemployment_15plus['country'] == 'USA') & (df_unemployment_15plus['year'] == 1947)]

    country  year  unemployment_15plus
209     USA  1947                  3.9

In [27]:
df_pop[(df_pop['country'] == 'USA') & (df_pop['year'] == 1947)]

      country  year   population
29145     USA  1947  148000000.0

In [28]:
df_merged['pop_unemployment'] = df_merged['population'] * df_merged['unemployment_15plus'] /100

In [29]:
df_merged[df_merged['country'] == 'Russia']

     country  year   population  unemployment_15plus  pop_unemployment
1152  Russia  1992  149000000.0                 5.18         7718200.0
1235  Russia  1993  148000000.0                 5.88         8702400.0
1324  Russia  1994  148000000.0                 8.13        12032400.0
1419  Russia  1995  148000000.0                 9.45        13986000.0
1519  Russia  1996  148000000.0                 9.67        14311600.0
1617  Russia  1997  148000000.0                11.80        17464000.0
1713  Russia  1998  148000000.0                13.30        19684000.0
1813  Russia  1999  147000000.0                13.00        19110000.0
1920  Russia  2000  147000000.0                10.60        15582000.0
2028  Russia  2001  146000000.0                 8.98        13110800.0
2134  Russia  2002  146000000.0                 7.88        11504800.0
2246  Russia  2003  146000000.0                 8.21        11986600.0
2356  Russia  2004  145000000.0                 7.76        11252000.0
2477  Russia  2005  145000000.0                 7.12        10324000.0
2589  Russia  2006  144000000.0                 7.06        10166400.0
2710  Russia  2007  144000000.0                 6.00         8640000.0
2823  Russia  2008  144000000.0                 6.21         8942400.0
2940  Russia  2009  144000000.0                 8.30        11952000.0
3068  Russia  2010  144000000.0                 7.37        10612800.0
3188  Russia  2011  144000000.0                 6.54         9417600.0
3313  Russia  2012  144000000.0                 5.44         7833600.0
3435  Russia  2013  145000000.0                 5.46         7917000.0
3562  Russia  2014  145000000.0                 5.16         7482000.0
3681  Russia  2015  145000000.0                 5.57         8076500.0
3798  Russia  2016  146000000.0                 5.56         8117600.0
3924  Russia  2017  146000000.0                 5.21         7606600.0
4040  Russia  2018  146000000.0                 4.85         7081000.0
4151  Russia  2019  147000000.0                 4.50         6615000.0
4241  Russia  2020  146000000.0                 5.59         8161400.0

In [30]:
df_merged['year'].value_counts()

year
2014    129
2010    125
2017    124
2009    123
2012    123
       ...
1950      1
1947      1
1948      1
1951      1
1952      1
Name: count, Length: 74, dtype: int64

In [31]:
df_merged['year'].unique()

array([1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957,
       1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968,
       1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979,
       1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990,
       1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001,
       2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012,
       2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020])

In [32]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4258 entries, 0 to 4257
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              4258 non-null   object
 1   year                 4258 non-null   int64
 2   population           4258 non-null   float64
 3   unemployment_15plus  4258 non-null   float64
 4   pop_unemployment     4258 non-null   float64
dtypes: float64(3), int64(1), object(1)
memory usage: 166.5+ KB

In [164]:
df_merged.columns

Index(['country', 'year', 'population', 'unemployment_15plus',
       'pop_unemployment'],
      dtype='object')

In [160]:
df_merged[df_merged['year']==1952]

  country  year   population  unemployment_15plus  pop_unemployment
5     USA  1952  159000000.0                  3.0         4770000.0

In [146]:
df_pop_2023 = df_pop[df_pop['year']<=2023].reset_index().drop(columns=['index'])

In [147]:
df_pop_predict = df_pop[df_pop['year']>2023].reset_index().drop(columns=['index'])

In [148]:
df_pop_2023

            country  year  population
0       Afghanistan  1800   3280000.0
1            Angola  1800   1570000.0
2           Albania  1800    400000.0
3           Andorra  1800      2650.0
4               UAE  1800     40200.0
...             ...   ...         ...
44100         Samoa  2023    217000.0
44101         Yemen  2023  39400000.0
44102  South Africa  2023  63200000.0
44103        Zambia  2023  20700000.0
44104      Zimbabwe  2023  16300000.0

[44105 rows x 3 columns]

In [149]:
df_pop_predict

            country  year   population
0       Afghanistan  2024   42600000.0
1            Angola  2024   37900000.0
2           Albania  2024    2790000.0
3           Andorra  2024      81900.0
4               UAE  2024   11000000.0
...             ...   ...          ...
15087         Samoa  2100     384000.0
15088         Yemen  2100  110000000.0
15089  South Africa  2100   94300000.0
15090        Zambia  2100   64500000.0
15091      Zimbabwe  2100   37200000.0

[15092 rows x 3 columns]

In [150]:
df_concat = pd.concat([df_pop_2023, df_pop_predict], ignore_index=True)

In [151]:
df_concat

            country  year   population
0       Afghanistan  1800    3280000.0
1            Angola  1800    1570000.0
2           Albania  1800     400000.0
3           Andorra  1800       2650.0
4               UAE  1800      40200.0
...             ...   ...          ...
59192         Samoa  2100     384000.0
59193         Yemen  2100  110000000.0
59194  South Africa  2100   94300000.0
59195        Zambia  2100   64500000.0
59196      Zimbabwe  2100   37200000.0

[59197 rows x 3 columns]

In [152]:
df_concat.loc[0]

country       Afghanistan
year                 1800
population      3280000.0
Name: 0, dtype: object

In [33]:
pd.pivot_table(
    df_merged[df_merged['year']>=2020], 
    index='country', 
    values=['pop_unemployment', 'unemployment_15plus'], 
    aggfunc='mean',
).sort_values('unemployment_15plus')

              pop_unemployment  unemployment_15plus
country
El Salvador             3738.0                 0.06
Qatar                   3920.0                 0.14
Thailand              787600.0                 1.10
Malawi                247650.0                 1.27
Vietnam              2344590.0                 2.39
...                        ...                  ...
Georgia               703000.0                18.50
Panama                797940.0                18.60
Botswana              590130.0                24.90
Palestine            1313130.0                25.90
South Africa        17695200.0                29.20

[83 rows x 2 columns]