In [1]:
# Задание:
# 1) Скачать 2 показателя с https://www.gapminder.org/data/
# 2) Предобрабоать данные:
#  - Преоброзовать в длинный формат
#  - Удалить null, если есть
#  - Преоброзовать типы
# 3) Объединить датафреймы через merge
# 4) Вычислить новый столбец используя оба показателя
# 5) Сделать сводную таблицу (pivot_table) по общему df

In [2]:
import pandas as pd

In [3]:
df_pop = pd.read_csv('../data/raw/pop.csv')

In [4]:
df_unemployment_15plus = pd.read_csv('../data/raw/aged_15plus_unemployment_rate_percent.csv')

In [5]:
df_pop

,country,1800,1801,1802,1803,1804,1805,1806,1807,1808,...,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100
0,Afghanistan,3.28M,3.28M,3.28M,3.28M,3.28M,3.28M,3.28M,3.28M,3.28M,...,124M,125M,126M,126M,127M,128M,128M,129M,130M,130M
1,Angola,1.57M,1.57M,1.57M,1.57M,1.57M,1.57M,1.57M,1.57M,1.57M,...,139M,140M,142M,143M,144M,145M,147M,148M,149M,150M
2,Albania,400k,402k,404k,405k,407k,409k,411k,413k,414k,...,1.34M,1.32M,1.3M,1.29M,1.27M,1.25M,1.23M,1.22M,1.2M,1.18M
3,Andorra,2650,2650,2650,2650,2650,2650,2650,2650,2650,...,52.8k,52.1k,51.5k,50.8k,50.2k,49.6k,49k,48.4k,47.8k,47.2k
4,UAE,40.2k,40.2k,40.2k,40.2k,40.2k,40.2k,40.2k,40.2k,40.2k,...,24.1M,24.3M,24.5M,24.7M,25M,25.2M,25.4M,25.7M,25.9M,26.1M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192,Samoa,47.3k,47.3k,47.3k,47.3k,47.3k,47.3k,47.3k,47.2k,47.2k,...,370k,372k,374k,375k,377k,378k,380k,381k,382k,384k
193,Yemen,2.59M,2.59M,2.59M,2.59M,2.59M,2.59M,2.59M,2.59M,2.59M,...,107M,107M,107M,108M,108M,109M,109M,109M,110M,110M
194,South Africa,1.45M,1.45M,1.46M,1.46M,1.47M,1.47M,1.48M,1.49M,1.49M,...,92.4M,92.6M,92.9M,93.1M,93.3M,93.5M,93.7M,93.9M,94.1M,94.3M
195,Zambia,747k,758k,770k,782k,794k,806k,818k,831k,843k,...,61.1M,61.5M,61.9M,62.3M,62.7M,63.1M,63.4M,63.8M,64.1M,64.5M
196,Zimbabwe,1.09M,1.09M,1.09M,1.09M,1.09M,1.09M,1.09M,1.09M,1.09M,...,36.3M,36.4M,36.5M,36.6M,36.7M,36.8M,36.9M,37M,37.1M,37.2M

In [6]:
df_pop = pd.melt(
    df_pop, 
    id_vars='country', 
    var_name='year', 
    value_name='population',
)

In [7]:
df_pop

            country  year population
0       Afghanistan  1800      3.28M
1            Angola  1800      1.57M
2           Albania  1800       400k
3           Andorra  1800       2650
4               UAE  1800      40.2k
...             ...   ...        ...
59292         Samoa  2100       384k
59293         Yemen  2100       110M
59294  South Africa  2100      94.3M
59295        Zambia  2100      64.5M
59296      Zimbabwe  2100      37.2M

[59297 rows x 3 columns]

In [8]:
df_unemployment_15plus = pd.melt(
    df_unemployment_15plus, 
    id_vars='country', 
    var_name='year', 
    value_name='unemployment_15plus',
)

In [9]:
df_pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59297 entries, 0 to 59296
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     59297 non-null  object
 1   year        59297 non-null  object
 2   population  59197 non-null  object
dtypes: object(3)
memory usage: 1.4+ MB

In [10]:
df_pop = df_pop.dropna()

In [11]:
df_pop['year'] = pd.to_numeric(df_pop['year'])

C:\Users\Администратор\AppData\Local\Temp\ipykernel_3468\1693227212.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pop['year'] = pd.to_numeric(df_pop['year'])

In [12]:
df_pop['population'] = pd.to_numeric(
    ((
        df_pop['population'].astype(str)\
        .str.replace('M', 'e6'))\
        .str.replace('k', 'e3'))\
        .str.replace('B', 'e9')\
)

C:\Users\Администратор\AppData\Local\Temp\ipykernel_3468\889420809.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pop['population'] = pd.to_numeric(

In [13]:
df_pop.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59197 entries, 0 to 59296
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     59197 non-null  object
 1   year        59197 non-null  int64
 2   population  59197 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.8+ MB

In [14]:
df_unemployment_15plus.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16428 entries, 0 to 16427
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              16428 non-null  object
 1   year                 16428 non-null  object
 2   unemployment_15plus  4698 non-null   float64
dtypes: float64(1), object(2)
memory usage: 385.2+ KB

In [15]:
df_unemployment_15plus = df_unemployment_15plus.dropna()

In [16]:
df_unemployment_15plus['year'] = pd.to_numeric(
    df_unemployment_15plus['year']
)

In [17]:
df_unemployment_15plus.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4698 entries, 209 to 16425
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              4698 non-null   object
 1   year                 4698 non-null   int64
 2   unemployment_15plus  4698 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 146.8+ KB

In [18]:
df_merged = pd.merge(
    df_pop, 
    df_unemployment_15plus, 
    how='inner',
    left_on=['country', 'year'],
    right_on=['country', 'year']
)

In [19]:
df_merged['pop_unemployment'] = df_merged['population'] * df_merged['unemployment_15plus'] /100

In [20]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4258 entries, 0 to 4257
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   country              4258 non-null   object
 1   year                 4258 non-null   int64
 2   population           4258 non-null   float64
 3   unemployment_15plus  4258 non-null   float64
 4   pop_unemployment     4258 non-null   float64
dtypes: float64(3), int64(1), object(1)
memory usage: 166.5+ KB

In [21]:
pd.pivot_table(
    df_merged[df_merged['year']>=2020], 
    index='country', 
    values=['pop_unemployment', 'unemployment_15plus'], 
    aggfunc=['mean', 'max'],
).sort_values(('max','unemployment_15plus'))

                         mean                                  max  \
             pop_unemployment unemployment_15plus pop_unemployment
country
El Salvador            3738.0                0.06           3738.0
Qatar                  3920.0                0.14           3920.0
Thailand             787600.0                1.10         787600.0
Malawi               247650.0                1.27         247650.0
Vietnam             2344590.0                2.39        2344590.0
...                       ...                 ...              ...
Georgia              703000.0               18.50         703000.0
Panama               797940.0               18.60         797940.0
Botswana             590130.0               24.90         590130.0
Palestine           1313130.0               25.90        1313130.0
South Africa       17695200.0               29.20       17695200.0


             unemployment_15plus
country
El Salvador                 0.06
Qatar                       0.14
Thailand                    1.10
Malawi                      1.27
Vietnam                     2.39
...                          ...
Georgia                    18.50
Panama                     18.60
Botswana                   24.90
Palestine                  25.90
South Africa               29.20

[83 rows x 4 columns]